[theme]
primaryColor = "#1E88E5"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8F9FA"
textColor = "#424242"
font = "sans serif"

[server]
maxUploadSize = 20
enableCORS = false

[browser]
gatherUsageStats = false
